name: vacation_homework_app
description: "A new Flutter project."

version: 1.0.0+2

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  flutter_screenutil: ^5.9.0
  flutter_dotenv: ^5.1.0
  cupertino_icons: ^1.0.8
  dio: ^5.4.0
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  table_calendar: ^3.0.9
  flutter_animate: ^4.3.0
  fluttertoast: ^8.2.2

  firebase_core: ^3.14.0
  firebase_messaging: ^15.2.7
  flutter_local_notifications: ^17.0.0
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.13.1


flutter:
  uses-material-design: true
  fonts:
    - family: nanum_matitnen
      fonts:
        - asset: assets/fonts/nanum_matitnen.ttf
  assets:
    - .env
    - assets/images/logo.svg
    - assets/images/splash.png
    - assets/images/app_icon.png
    - assets/images/good_sign.png


flutter_native_splash:
  color: "#ffffff" # 배경색
  image: assets/images/splash.png # 스플래시에 사용할 이미지 경로
  android: true
  ios: true
  fullscreen: true


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"  # ← 아이콘 이미지 경로
  min_sdk_android: 21  # (옵션) 필요 시 설정
